/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SummaryGeneratorRouteImport } from './routes/summary-generator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalaryAnalyzerRouteImport } from './routes/salary-analyzer'
import { Route as ResumeTailorRouteImport } from './routes/resume-tailor'
import { Route as ResumeScoreRouteImport } from './routes/resume-score'
import { Route as ResumeExamplesRouteImport } from './routes/resume-examples'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResignationLetterRouteImport } from './routes/resignation-letter'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecruiterMatchRouteImport } from './routes/recruiter-match'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PkRouteImport } from './routes/pk'
import { Route as PdfScannerRouteImport } from './routes/pdf-scanner'
import { Route as ManageSubscriptionRouteImport } from './routes/manage-subscription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinBioRouteImport } from './routes/linkedin-bio'
import { Route as KeywordScannerRouteImport } from './routes/keyword-scanner'
import { Route as JobBoardRouteImport } from './routes/job-board'
import { Route as InterviewPrepRouteImport } from './routes/interview-prep'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulletWriterRouteImport } from './routes/bullet-writer'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AtsCheckerRouteImport } from './routes/ats-checker'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeExamplesIndexRouteImport } from './routes/resume-examples.index'
import { Route as PkIndexRouteImport } from './routes/pk.index'
import { Route as ResumeExamplesSlugRouteImport } from './routes/resume-examples.$slug'
import { Route as PremiumSuccessRouteImport } from './routes/premium/success'
import { Route as PkSlugRouteImport } from './routes/pk.$slug'
import { Route as CompareAiresumiVsZetyRouteImport } from './routes/compare.airesumi-vs-zety'
import { Route as CompareAiresumiVsReziRouteImport } from './routes/compare.airesumi-vs-rezi'
import { Route as CompareAiresumiVsKickresumeRouteImport } from './routes/compare.airesumi-vs-kickresume'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiUploadCvRouteImport } from './routes/api/upload-cv'
import { Route as ApiTailorResumeRouteImport } from './routes/api/tailor-resume'
import { Route as ApiSubscriptionStatusRouteImport } from './routes/api/subscription-status'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiScanKeywordsRouteImport } from './routes/api/scan-keywords'
import { Route as ApiRoastResumeRouteImport } from './routes/api/roast-resume'
import { Route as ApiParseCvTextRouteImport } from './routes/api/parse-cv-text'
import { Route as ApiGenerateSummaryRouteImport } from './routes/api/generate-summary'
import { Route as ApiGenerateResumeRouteImport } from './routes/api/generate-resume'
import { Route as ApiGenerateResignationRouteImport } from './routes/api/generate-resignation'
import { Route as ApiGenerateLinkedinBioRouteImport } from './routes/api/generate-linkedin-bio'
import { Route as ApiGenerateCoverLetterRouteImport } from './routes/api/generate-cover-letter'
import { Route as ApiGenerateBulletsRouteImport } from './routes/api/generate-bullets'
import { Route as ApiCreatePortalSessionRouteImport } from './routes/api/create-portal-session'
import { Route as ApiCreateCheckoutRouteImport } from './routes/api/create-checkout'
import { Route as ApiAnalyzeAtsRouteImport } from './routes/api/analyze-ats'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as ApiPublicOgSlugRouteImport } from './routes/api/public/og.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryGeneratorRoute = SummaryGeneratorRouteImport.update({
  id: '/summary-generator',
  path: '/summary-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryAnalyzerRoute = SalaryAnalyzerRouteImport.update({
  id: '/salary-analyzer',
  path: '/salary-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTailorRoute = ResumeTailorRouteImport.update({
  id: '/resume-tailor',
  path: '/resume-tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeScoreRoute = ResumeScoreRouteImport.update({
  id: '/resume-score',
  path: '/resume-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExamplesRoute = ResumeExamplesRouteImport.update({
  id: '/resume-examples',
  path: '/resume-examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResignationLetterRoute = ResignationLetterRouteImport.update({
  id: '/resignation-letter',
  path: '/resignation-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterMatchRoute = RecruiterMatchRouteImport.update({
  id: '/recruiter-match',
  path: '/recruiter-match',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PkRoute = PkRouteImport.update({
  id: '/pk',
  path: '/pk',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfScannerRoute = PdfScannerRouteImport.update({
  id: '/pdf-scanner',
  path: '/pdf-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSubscriptionRoute = ManageSubscriptionRouteImport.update({
  id: '/manage-subscription',
  path: '/manage-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinBioRoute = LinkedinBioRouteImport.update({
  id: '/linkedin-bio',
  path: '/linkedin-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordScannerRoute = KeywordScannerRouteImport.update({
  id: '/keyword-scanner',
  path: '/keyword-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const JobBoardRoute = JobBoardRouteImport.update({
  id: '/job-board',
  path: '/job-board',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepRoute = InterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletWriterRoute = BulletWriterRouteImport.update({
  id: '/bullet-writer',
  path: '/bullet-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsCheckerRoute = AtsCheckerRouteImport.update({
  id: '/ats-checker',
  path: '/ats-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExamplesIndexRoute = ResumeExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeExamplesRoute,
} as any)
const PkIndexRoute = PkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PkRoute,
} as any)
const ResumeExamplesSlugRoute = ResumeExamplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResumeExamplesRoute,
} as any)
const PremiumSuccessRoute = PremiumSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PremiumRoute,
} as any)
const PkSlugRoute = PkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PkRoute,
} as any)
const CompareAiresumiVsZetyRoute = CompareAiresumiVsZetyRouteImport.update({
  id: '/compare/airesumi-vs-zety',
  path: '/compare/airesumi-vs-zety',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareAiresumiVsReziRoute = CompareAiresumiVsReziRouteImport.update({
  id: '/compare/airesumi-vs-rezi',
  path: '/compare/airesumi-vs-rezi',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareAiresumiVsKickresumeRoute =
  CompareAiresumiVsKickresumeRouteImport.update({
    id: '/compare/airesumi-vs-kickresume',
    path: '/compare/airesumi-vs-kickresume',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCvRoute = ApiUploadCvRouteImport.update({
  id: '/api/upload-cv',
  path: '/api/upload-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailorResumeRoute = ApiTailorResumeRouteImport.update({
  id: '/api/tailor-resume',
  path: '/api/tailor-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionStatusRoute = ApiSubscriptionStatusRouteImport.update({
  id: '/api/subscription-status',
  path: '/api/subscription-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanKeywordsRoute = ApiScanKeywordsRouteImport.update({
  id: '/api/scan-keywords',
  path: '/api/scan-keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoastResumeRoute = ApiRoastResumeRouteImport.update({
  id: '/api/roast-resume',
  path: '/api/roast-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseCvTextRoute = ApiParseCvTextRouteImport.update({
  id: '/api/parse-cv-text',
  path: '/api/parse-cv-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSummaryRoute = ApiGenerateSummaryRouteImport.update({
  id: '/api/generate-summary',
  path: '/api/generate-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateResumeRoute = ApiGenerateResumeRouteImport.update({
  id: '/api/generate-resume',
  path: '/api/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateResignationRoute = ApiGenerateResignationRouteImport.update({
  id: '/api/generate-resignation',
  path: '/api/generate-resignation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLinkedinBioRoute = ApiGenerateLinkedinBioRouteImport.update({
  id: '/api/generate-linkedin-bio',
  path: '/api/generate-linkedin-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCoverLetterRoute = ApiGenerateCoverLetterRouteImport.update({
  id: '/api/generate-cover-letter',
  path: '/api/generate-cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateBulletsRoute = ApiGenerateBulletsRouteImport.update({
  id: '/api/generate-bullets',
  path: '/api/generate-bullets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePortalSessionRoute = ApiCreatePortalSessionRouteImport.update({
  id: '/api/create-portal-session',
  path: '/api/create-portal-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateCheckoutRoute = ApiCreateCheckoutRouteImport.update({
  id: '/api/create-checkout',
  path: '/api/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeAtsRoute = ApiAnalyzeAtsRouteImport.update({
  id: '/api/analyze-ats',
  path: '/api/analyze-ats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgSlugRoute = ApiPublicOgSlugRouteImport.update({
  id: '/api/public/og/$slug',
  path: '/api/public/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/blog': typeof BlogRouteWithChildren
  '/bullet-writer': typeof BulletWriterRoute
  '/contact': typeof ContactRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/job-board': typeof JobBoardRoute
  '/keyword-scanner': typeof KeywordScannerRoute
  '/linkedin-bio': typeof LinkedinBioRoute
  '/login': typeof LoginRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/pdf-scanner': typeof PdfScannerRoute
  '/pk': typeof PkRouteWithChildren
  '/premium': typeof PremiumRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/recruiter-match': typeof RecruiterMatchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resignation-letter': typeof ResignationLetterRoute
  '/resume': typeof ResumeRoute
  '/resume-examples': typeof ResumeExamplesRouteWithChildren
  '/resume-score': typeof ResumeScoreRoute
  '/resume-tailor': typeof ResumeTailorRoute
  '/salary-analyzer': typeof SalaryAnalyzerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summary-generator': typeof SummaryGeneratorRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/create-portal-session': typeof ApiCreatePortalSessionRoute
  '/api/generate-bullets': typeof ApiGenerateBulletsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-linkedin-bio': typeof ApiGenerateLinkedinBioRoute
  '/api/generate-resignation': typeof ApiGenerateResignationRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/roast-resume': typeof ApiRoastResumeRoute
  '/api/scan-keywords': typeof ApiScanKeywordsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/subscription-status': typeof ApiSubscriptionStatusRoute
  '/api/tailor-resume': typeof ApiTailorResumeRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/airesumi-vs-kickresume': typeof CompareAiresumiVsKickresumeRoute
  '/compare/airesumi-vs-rezi': typeof CompareAiresumiVsReziRoute
  '/compare/airesumi-vs-zety': typeof CompareAiresumiVsZetyRoute
  '/pk/$slug': typeof PkSlugRoute
  '/premium/success': typeof PremiumSuccessRoute
  '/resume-examples/$slug': typeof ResumeExamplesSlugRoute
  '/pk/': typeof PkIndexRoute
  '/resume-examples/': typeof ResumeExamplesIndexRoute
  '/api/public/og/$slug': typeof ApiPublicOgSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/blog': typeof BlogRouteWithChildren
  '/bullet-writer': typeof BulletWriterRoute
  '/contact': typeof ContactRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/job-board': typeof JobBoardRoute
  '/keyword-scanner': typeof KeywordScannerRoute
  '/linkedin-bio': typeof LinkedinBioRoute
  '/login': typeof LoginRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/pdf-scanner': typeof PdfScannerRoute
  '/premium': typeof PremiumRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/recruiter-match': typeof RecruiterMatchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resignation-letter': typeof ResignationLetterRoute
  '/resume': typeof ResumeRoute
  '/resume-score': typeof ResumeScoreRoute
  '/resume-tailor': typeof ResumeTailorRoute
  '/salary-analyzer': typeof SalaryAnalyzerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summary-generator': typeof SummaryGeneratorRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/create-portal-session': typeof ApiCreatePortalSessionRoute
  '/api/generate-bullets': typeof ApiGenerateBulletsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-linkedin-bio': typeof ApiGenerateLinkedinBioRoute
  '/api/generate-resignation': typeof ApiGenerateResignationRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/roast-resume': typeof ApiRoastResumeRoute
  '/api/scan-keywords': typeof ApiScanKeywordsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/subscription-status': typeof ApiSubscriptionStatusRoute
  '/api/tailor-resume': typeof ApiTailorResumeRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/airesumi-vs-kickresume': typeof CompareAiresumiVsKickresumeRoute
  '/compare/airesumi-vs-rezi': typeof CompareAiresumiVsReziRoute
  '/compare/airesumi-vs-zety': typeof CompareAiresumiVsZetyRoute
  '/pk/$slug': typeof PkSlugRoute
  '/premium/success': typeof PremiumSuccessRoute
  '/resume-examples/$slug': typeof ResumeExamplesSlugRoute
  '/pk': typeof PkIndexRoute
  '/resume-examples': typeof ResumeExamplesIndexRoute
  '/api/public/og/$slug': typeof ApiPublicOgSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-checker': typeof AtsCheckerRoute
  '/blog': typeof BlogRouteWithChildren
  '/bullet-writer': typeof BulletWriterRoute
  '/contact': typeof ContactRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/job-board': typeof JobBoardRoute
  '/keyword-scanner': typeof KeywordScannerRoute
  '/linkedin-bio': typeof LinkedinBioRoute
  '/login': typeof LoginRoute
  '/manage-subscription': typeof ManageSubscriptionRoute
  '/pdf-scanner': typeof PdfScannerRoute
  '/pk': typeof PkRouteWithChildren
  '/premium': typeof PremiumRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/recruiter-match': typeof RecruiterMatchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resignation-letter': typeof ResignationLetterRoute
  '/resume': typeof ResumeRoute
  '/resume-examples': typeof ResumeExamplesRouteWithChildren
  '/resume-score': typeof ResumeScoreRoute
  '/resume-tailor': typeof ResumeTailorRoute
  '/salary-analyzer': typeof SalaryAnalyzerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summary-generator': typeof SummaryGeneratorRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/api/analyze-ats': typeof ApiAnalyzeAtsRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/create-portal-session': typeof ApiCreatePortalSessionRoute
  '/api/generate-bullets': typeof ApiGenerateBulletsRoute
  '/api/generate-cover-letter': typeof ApiGenerateCoverLetterRoute
  '/api/generate-linkedin-bio': typeof ApiGenerateLinkedinBioRoute
  '/api/generate-resignation': typeof ApiGenerateResignationRoute
  '/api/generate-resume': typeof ApiGenerateResumeRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/parse-cv-text': typeof ApiParseCvTextRoute
  '/api/roast-resume': typeof ApiRoastResumeRoute
  '/api/scan-keywords': typeof ApiScanKeywordsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/subscription-status': typeof ApiSubscriptionStatusRoute
  '/api/tailor-resume': typeof ApiTailorResumeRoute
  '/api/upload-cv': typeof ApiUploadCvRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/airesumi-vs-kickresume': typeof CompareAiresumiVsKickresumeRoute
  '/compare/airesumi-vs-rezi': typeof CompareAiresumiVsReziRoute
  '/compare/airesumi-vs-zety': typeof CompareAiresumiVsZetyRoute
  '/pk/$slug': typeof PkSlugRoute
  '/premium/success': typeof PremiumSuccessRoute
  '/resume-examples/$slug': typeof ResumeExamplesSlugRoute
  '/pk/': typeof PkIndexRoute
  '/resume-examples/': typeof ResumeExamplesIndexRoute
  '/api/public/og/$slug': typeof ApiPublicOgSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/blog'
    | '/bullet-writer'
    | '/contact'
    | '/cover-letter'
    | '/dashboard'
    | '/examples'
    | '/interview-prep'
    | '/job-board'
    | '/keyword-scanner'
    | '/linkedin-bio'
    | '/login'
    | '/manage-subscription'
    | '/pdf-scanner'
    | '/pk'
    | '/premium'
    | '/privacy'
    | '/recruiter-match'
    | '/reset-password'
    | '/resignation-letter'
    | '/resume'
    | '/resume-examples'
    | '/resume-score'
    | '/resume-tailor'
    | '/salary-analyzer'
    | '/sitemap.xml'
    | '/summary-generator'
    | '/terms'
    | '/admin/blog'
    | '/api/analyze-ats'
    | '/api/create-checkout'
    | '/api/create-portal-session'
    | '/api/generate-bullets'
    | '/api/generate-cover-letter'
    | '/api/generate-linkedin-bio'
    | '/api/generate-resignation'
    | '/api/generate-resume'
    | '/api/generate-summary'
    | '/api/parse-cv-text'
    | '/api/roast-resume'
    | '/api/scan-keywords'
    | '/api/stripe-webhook'
    | '/api/subscription-status'
    | '/api/tailor-resume'
    | '/api/upload-cv'
    | '/auth/callback'
    | '/blog/$slug'
    | '/compare/airesumi-vs-kickresume'
    | '/compare/airesumi-vs-rezi'
    | '/compare/airesumi-vs-zety'
    | '/pk/$slug'
    | '/premium/success'
    | '/resume-examples/$slug'
    | '/pk/'
    | '/resume-examples/'
    | '/api/public/og/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ats-checker'
    | '/blog'
    | '/bullet-writer'
    | '/contact'
    | '/cover-letter'
    | '/dashboard'
    | '/examples'
    | '/interview-prep'
    | '/job-board'
    | '/keyword-scanner'
    | '/linkedin-bio'
    | '/login'
    | '/manage-subscription'
    | '/pdf-scanner'
    | '/premium'
    | '/privacy'
    | '/recruiter-match'
    | '/reset-password'
    | '/resignation-letter'
    | '/resume'
    | '/resume-score'
    | '/resume-tailor'
    | '/salary-analyzer'
    | '/sitemap.xml'
    | '/summary-generator'
    | '/terms'
    | '/admin/blog'
    | '/api/analyze-ats'
    | '/api/create-checkout'
    | '/api/create-portal-session'
    | '/api/generate-bullets'
    | '/api/generate-cover-letter'
    | '/api/generate-linkedin-bio'
    | '/api/generate-resignation'
    | '/api/generate-resume'
    | '/api/generate-summary'
    | '/api/parse-cv-text'
    | '/api/roast-resume'
    | '/api/scan-keywords'
    | '/api/stripe-webhook'
    | '/api/subscription-status'
    | '/api/tailor-resume'
    | '/api/upload-cv'
    | '/auth/callback'
    | '/blog/$slug'
    | '/compare/airesumi-vs-kickresume'
    | '/compare/airesumi-vs-rezi'
    | '/compare/airesumi-vs-zety'
    | '/pk/$slug'
    | '/premium/success'
    | '/resume-examples/$slug'
    | '/pk'
    | '/resume-examples'
    | '/api/public/og/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ats-checker'
    | '/blog'
    | '/bullet-writer'
    | '/contact'
    | '/cover-letter'
    | '/dashboard'
    | '/examples'
    | '/interview-prep'
    | '/job-board'
    | '/keyword-scanner'
    | '/linkedin-bio'
    | '/login'
    | '/manage-subscription'
    | '/pdf-scanner'
    | '/pk'
    | '/premium'
    | '/privacy'
    | '/recruiter-match'
    | '/reset-password'
    | '/resignation-letter'
    | '/resume'
    | '/resume-examples'
    | '/resume-score'
    | '/resume-tailor'
    | '/salary-analyzer'
    | '/sitemap.xml'
    | '/summary-generator'
    | '/terms'
    | '/admin/blog'
    | '/api/analyze-ats'
    | '/api/create-checkout'
    | '/api/create-portal-session'
    | '/api/generate-bullets'
    | '/api/generate-cover-letter'
    | '/api/generate-linkedin-bio'
    | '/api/generate-resignation'
    | '/api/generate-resume'
    | '/api/generate-summary'
    | '/api/parse-cv-text'
    | '/api/roast-resume'
    | '/api/scan-keywords'
    | '/api/stripe-webhook'
    | '/api/subscription-status'
    | '/api/tailor-resume'
    | '/api/upload-cv'
    | '/auth/callback'
    | '/blog/$slug'
    | '/compare/airesumi-vs-kickresume'
    | '/compare/airesumi-vs-rezi'
    | '/compare/airesumi-vs-zety'
    | '/pk/$slug'
    | '/premium/success'
    | '/resume-examples/$slug'
    | '/pk/'
    | '/resume-examples/'
    | '/api/public/og/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtsCheckerRoute: typeof AtsCheckerRoute
  BlogRoute: typeof BlogRouteWithChildren
  BulletWriterRoute: typeof BulletWriterRoute
  ContactRoute: typeof ContactRoute
  CoverLetterRoute: typeof CoverLetterRoute
  DashboardRoute: typeof DashboardRoute
  ExamplesRoute: typeof ExamplesRoute
  InterviewPrepRoute: typeof InterviewPrepRoute
  JobBoardRoute: typeof JobBoardRoute
  KeywordScannerRoute: typeof KeywordScannerRoute
  LinkedinBioRoute: typeof LinkedinBioRoute
  LoginRoute: typeof LoginRoute
  ManageSubscriptionRoute: typeof ManageSubscriptionRoute
  PdfScannerRoute: typeof PdfScannerRoute
  PkRoute: typeof PkRouteWithChildren
  PremiumRoute: typeof PremiumRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RecruiterMatchRoute: typeof RecruiterMatchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResignationLetterRoute: typeof ResignationLetterRoute
  ResumeRoute: typeof ResumeRoute
  ResumeExamplesRoute: typeof ResumeExamplesRouteWithChildren
  ResumeScoreRoute: typeof ResumeScoreRoute
  ResumeTailorRoute: typeof ResumeTailorRoute
  SalaryAnalyzerRoute: typeof SalaryAnalyzerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SummaryGeneratorRoute: typeof SummaryGeneratorRoute
  TermsRoute: typeof TermsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  ApiAnalyzeAtsRoute: typeof ApiAnalyzeAtsRoute
  ApiCreateCheckoutRoute: typeof ApiCreateCheckoutRoute
  ApiCreatePortalSessionRoute: typeof ApiCreatePortalSessionRoute
  ApiGenerateBulletsRoute: typeof ApiGenerateBulletsRoute
  ApiGenerateCoverLetterRoute: typeof ApiGenerateCoverLetterRoute
  ApiGenerateLinkedinBioRoute: typeof ApiGenerateLinkedinBioRoute
  ApiGenerateResignationRoute: typeof ApiGenerateResignationRoute
  ApiGenerateResumeRoute: typeof ApiGenerateResumeRoute
  ApiGenerateSummaryRoute: typeof ApiGenerateSummaryRoute
  ApiParseCvTextRoute: typeof ApiParseCvTextRoute
  ApiRoastResumeRoute: typeof ApiRoastResumeRoute
  ApiScanKeywordsRoute: typeof ApiScanKeywordsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiSubscriptionStatusRoute: typeof ApiSubscriptionStatusRoute
  ApiTailorResumeRoute: typeof ApiTailorResumeRoute
  ApiUploadCvRoute: typeof ApiUploadCvRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CompareAiresumiVsKickresumeRoute: typeof CompareAiresumiVsKickresumeRoute
  CompareAiresumiVsReziRoute: typeof CompareAiresumiVsReziRoute
  CompareAiresumiVsZetyRoute: typeof CompareAiresumiVsZetyRoute
  ApiPublicOgSlugRoute: typeof ApiPublicOgSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary-generator': {
      id: '/summary-generator'
      path: '/summary-generator'
      fullPath: '/summary-generator'
      preLoaderRoute: typeof SummaryGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-analyzer': {
      id: '/salary-analyzer'
      path: '/salary-analyzer'
      fullPath: '/salary-analyzer'
      preLoaderRoute: typeof SalaryAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-tailor': {
      id: '/resume-tailor'
      path: '/resume-tailor'
      fullPath: '/resume-tailor'
      preLoaderRoute: typeof ResumeTailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-score': {
      id: '/resume-score'
      path: '/resume-score'
      fullPath: '/resume-score'
      preLoaderRoute: typeof ResumeScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-examples': {
      id: '/resume-examples'
      path: '/resume-examples'
      fullPath: '/resume-examples'
      preLoaderRoute: typeof ResumeExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resignation-letter': {
      id: '/resignation-letter'
      path: '/resignation-letter'
      fullPath: '/resignation-letter'
      preLoaderRoute: typeof ResignationLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-match': {
      id: '/recruiter-match'
      path: '/recruiter-match'
      fullPath: '/recruiter-match'
      preLoaderRoute: typeof RecruiterMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pk': {
      id: '/pk'
      path: '/pk'
      fullPath: '/pk'
      preLoaderRoute: typeof PkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-scanner': {
      id: '/pdf-scanner'
      path: '/pdf-scanner'
      fullPath: '/pdf-scanner'
      preLoaderRoute: typeof PdfScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-subscription': {
      id: '/manage-subscription'
      path: '/manage-subscription'
      fullPath: '/manage-subscription'
      preLoaderRoute: typeof ManageSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-bio': {
      id: '/linkedin-bio'
      path: '/linkedin-bio'
      fullPath: '/linkedin-bio'
      preLoaderRoute: typeof LinkedinBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyword-scanner': {
      id: '/keyword-scanner'
      path: '/keyword-scanner'
      fullPath: '/keyword-scanner'
      preLoaderRoute: typeof KeywordScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-board': {
      id: '/job-board'
      path: '/job-board'
      fullPath: '/job-board'
      preLoaderRoute: typeof JobBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep': {
      id: '/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof InterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bullet-writer': {
      id: '/bullet-writer'
      path: '/bullet-writer'
      fullPath: '/bullet-writer'
      preLoaderRoute: typeof BulletWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-checker': {
      id: '/ats-checker'
      path: '/ats-checker'
      fullPath: '/ats-checker'
      preLoaderRoute: typeof AtsCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-examples/': {
      id: '/resume-examples/'
      path: '/'
      fullPath: '/resume-examples/'
      preLoaderRoute: typeof ResumeExamplesIndexRouteImport
      parentRoute: typeof ResumeExamplesRoute
    }
    '/pk/': {
      id: '/pk/'
      path: '/'
      fullPath: '/pk/'
      preLoaderRoute: typeof PkIndexRouteImport
      parentRoute: typeof PkRoute
    }
    '/resume-examples/$slug': {
      id: '/resume-examples/$slug'
      path: '/$slug'
      fullPath: '/resume-examples/$slug'
      preLoaderRoute: typeof ResumeExamplesSlugRouteImport
      parentRoute: typeof ResumeExamplesRoute
    }
    '/premium/success': {
      id: '/premium/success'
      path: '/success'
      fullPath: '/premium/success'
      preLoaderRoute: typeof PremiumSuccessRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/pk/$slug': {
      id: '/pk/$slug'
      path: '/$slug'
      fullPath: '/pk/$slug'
      preLoaderRoute: typeof PkSlugRouteImport
      parentRoute: typeof PkRoute
    }
    '/compare/airesumi-vs-zety': {
      id: '/compare/airesumi-vs-zety'
      path: '/compare/airesumi-vs-zety'
      fullPath: '/compare/airesumi-vs-zety'
      preLoaderRoute: typeof CompareAiresumiVsZetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/airesumi-vs-rezi': {
      id: '/compare/airesumi-vs-rezi'
      path: '/compare/airesumi-vs-rezi'
      fullPath: '/compare/airesumi-vs-rezi'
      preLoaderRoute: typeof CompareAiresumiVsReziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/airesumi-vs-kickresume': {
      id: '/compare/airesumi-vs-kickresume'
      path: '/compare/airesumi-vs-kickresume'
      fullPath: '/compare/airesumi-vs-kickresume'
      preLoaderRoute: typeof CompareAiresumiVsKickresumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-cv': {
      id: '/api/upload-cv'
      path: '/api/upload-cv'
      fullPath: '/api/upload-cv'
      preLoaderRoute: typeof ApiUploadCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailor-resume': {
      id: '/api/tailor-resume'
      path: '/api/tailor-resume'
      fullPath: '/api/tailor-resume'
      preLoaderRoute: typeof ApiTailorResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription-status': {
      id: '/api/subscription-status'
      path: '/api/subscription-status'
      fullPath: '/api/subscription-status'
      preLoaderRoute: typeof ApiSubscriptionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-keywords': {
      id: '/api/scan-keywords'
      path: '/api/scan-keywords'
      fullPath: '/api/scan-keywords'
      preLoaderRoute: typeof ApiScanKeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roast-resume': {
      id: '/api/roast-resume'
      path: '/api/roast-resume'
      fullPath: '/api/roast-resume'
      preLoaderRoute: typeof ApiRoastResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-cv-text': {
      id: '/api/parse-cv-text'
      path: '/api/parse-cv-text'
      fullPath: '/api/parse-cv-text'
      preLoaderRoute: typeof ApiParseCvTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-summary': {
      id: '/api/generate-summary'
      path: '/api/generate-summary'
      fullPath: '/api/generate-summary'
      preLoaderRoute: typeof ApiGenerateSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-resume': {
      id: '/api/generate-resume'
      path: '/api/generate-resume'
      fullPath: '/api/generate-resume'
      preLoaderRoute: typeof ApiGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-resignation': {
      id: '/api/generate-resignation'
      path: '/api/generate-resignation'
      fullPath: '/api/generate-resignation'
      preLoaderRoute: typeof ApiGenerateResignationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-linkedin-bio': {
      id: '/api/generate-linkedin-bio'
      path: '/api/generate-linkedin-bio'
      fullPath: '/api/generate-linkedin-bio'
      preLoaderRoute: typeof ApiGenerateLinkedinBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-cover-letter': {
      id: '/api/generate-cover-letter'
      path: '/api/generate-cover-letter'
      fullPath: '/api/generate-cover-letter'
      preLoaderRoute: typeof ApiGenerateCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-bullets': {
      id: '/api/generate-bullets'
      path: '/api/generate-bullets'
      fullPath: '/api/generate-bullets'
      preLoaderRoute: typeof ApiGenerateBulletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-portal-session': {
      id: '/api/create-portal-session'
      path: '/api/create-portal-session'
      fullPath: '/api/create-portal-session'
      preLoaderRoute: typeof ApiCreatePortalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-checkout': {
      id: '/api/create-checkout'
      path: '/api/create-checkout'
      fullPath: '/api/create-checkout'
      preLoaderRoute: typeof ApiCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-ats': {
      id: '/api/analyze-ats'
      path: '/api/analyze-ats'
      fullPath: '/api/analyze-ats'
      preLoaderRoute: typeof ApiAnalyzeAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og/$slug': {
      id: '/api/public/og/$slug'
      path: '/api/public/og/$slug'
      fullPath: '/api/public/og/$slug'
      preLoaderRoute: typeof ApiPublicOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PkRouteChildren {
  PkSlugRoute: typeof PkSlugRoute
  PkIndexRoute: typeof PkIndexRoute
}

const PkRouteChildren: PkRouteChildren = {
  PkSlugRoute: PkSlugRoute,
  PkIndexRoute: PkIndexRoute,
}

const PkRouteWithChildren = PkRoute._addFileChildren(PkRouteChildren)

interface PremiumRouteChildren {
  PremiumSuccessRoute: typeof PremiumSuccessRoute
}

const PremiumRouteChildren: PremiumRouteChildren = {
  PremiumSuccessRoute: PremiumSuccessRoute,
}

const PremiumRouteWithChildren =
  PremiumRoute._addFileChildren(PremiumRouteChildren)

interface ResumeExamplesRouteChildren {
  ResumeExamplesSlugRoute: typeof ResumeExamplesSlugRoute
  ResumeExamplesIndexRoute: typeof ResumeExamplesIndexRoute
}

const ResumeExamplesRouteChildren: ResumeExamplesRouteChildren = {
  ResumeExamplesSlugRoute: ResumeExamplesSlugRoute,
  ResumeExamplesIndexRoute: ResumeExamplesIndexRoute,
}

const ResumeExamplesRouteWithChildren = ResumeExamplesRoute._addFileChildren(
  ResumeExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtsCheckerRoute: AtsCheckerRoute,
  BlogRoute: BlogRouteWithChildren,
  BulletWriterRoute: BulletWriterRoute,
  ContactRoute: ContactRoute,
  CoverLetterRoute: CoverLetterRoute,
  DashboardRoute: DashboardRoute,
  ExamplesRoute: ExamplesRoute,
  InterviewPrepRoute: InterviewPrepRoute,
  JobBoardRoute: JobBoardRoute,
  KeywordScannerRoute: KeywordScannerRoute,
  LinkedinBioRoute: LinkedinBioRoute,
  LoginRoute: LoginRoute,
  ManageSubscriptionRoute: ManageSubscriptionRoute,
  PdfScannerRoute: PdfScannerRoute,
  PkRoute: PkRouteWithChildren,
  PremiumRoute: PremiumRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RecruiterMatchRoute: RecruiterMatchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResignationLetterRoute: ResignationLetterRoute,
  ResumeRoute: ResumeRoute,
  ResumeExamplesRoute: ResumeExamplesRouteWithChildren,
  ResumeScoreRoute: ResumeScoreRoute,
  ResumeTailorRoute: ResumeTailorRoute,
  SalaryAnalyzerRoute: SalaryAnalyzerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SummaryGeneratorRoute: SummaryGeneratorRoute,
  TermsRoute: TermsRoute,
  AdminBlogRoute: AdminBlogRoute,
  ApiAnalyzeAtsRoute: ApiAnalyzeAtsRoute,
  ApiCreateCheckoutRoute: ApiCreateCheckoutRoute,
  ApiCreatePortalSessionRoute: ApiCreatePortalSessionRoute,
  ApiGenerateBulletsRoute: ApiGenerateBulletsRoute,
  ApiGenerateCoverLetterRoute: ApiGenerateCoverLetterRoute,
  ApiGenerateLinkedinBioRoute: ApiGenerateLinkedinBioRoute,
  ApiGenerateResignationRoute: ApiGenerateResignationRoute,
  ApiGenerateResumeRoute: ApiGenerateResumeRoute,
  ApiGenerateSummaryRoute: ApiGenerateSummaryRoute,
  ApiParseCvTextRoute: ApiParseCvTextRoute,
  ApiRoastResumeRoute: ApiRoastResumeRoute,
  ApiScanKeywordsRoute: ApiScanKeywordsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiSubscriptionStatusRoute: ApiSubscriptionStatusRoute,
  ApiTailorResumeRoute: ApiTailorResumeRoute,
  ApiUploadCvRoute: ApiUploadCvRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CompareAiresumiVsKickresumeRoute: CompareAiresumiVsKickresumeRoute,
  CompareAiresumiVsReziRoute: CompareAiresumiVsReziRoute,
  CompareAiresumiVsZetyRoute: CompareAiresumiVsZetyRoute,
  ApiPublicOgSlugRoute: ApiPublicOgSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
